language: android

env:
  - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"

jdk: oraclejdk8
# android-24需要jdk8+来编译

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.1
    - android-24
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

    #测试使用的系统镜像（其实使用下面的虚拟机就好了，这句不加也可以）
    - sys-img-armeabi-v7a-android-19

before_install:
  - chmod +x gradlew

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew build
